version: "3.0"
services:
  poll:
    build: ./poll
    depends_on:
      - "redis"
    links:
      - "redis"
      - "db"
    ports: 
      - "5000:80"
    networks: 
      - poll-tier
    environment:
      FLASK_APP: app.py
      FLASK_RUN_HOST: 0.0.0.0
  redis:
    image: redis:alpine
    expose: 
      - "6379"
    networks: 
      - poll-tier
      - back-tier
  worker:
    build: ./worker
    depends_on:
      - "redis"
      - "db"
    links:
      - "redis"
      - "db"
    networks: back-tier
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
  db:
    image: postgres:latest
    networks:
      - result-tier
      - back-tier
    volumes: 
      - ./schema.sql:/docker-entrypoint-initdb.d/init.sql
      - db-data:/usr/share/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
  result:
    build: ./result
    ports: 
      - "5001:80"
    networks: 
      - result-tier
    environment:
      PORT: 80
    depends_on:
      - "db"
    links:
      - "redis"
      - "db"
networks:
  poll-tier:
  result-tier:
  back-tier:
volumes:
  db-data:
